---
- name: Install and configure Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create nginx_default.j2 template
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name {{ server_name }};
              root /var/www/html;
              index index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

    - name: Create a soft link in the enabled sites
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Create index.html file
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "<html><body><h1>Hello from the web server</h1></body></html>"
        owner: root
        group: root
        mode: '0644'

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
