---
- name: Configure nginx to host the website
  hosts: client_vm
  become: true

  vars:
    server_name: "_"
    web_root: "/var/www/html"
    index_page: "index.html"
    nginx_config_path: "/etc/nginx/sites-available/default_new"

  tasks:
    - name: Install required packages
      apt:
        name:
          - php-fpm
          - python3-pymysql
        state: present

    - name: Ensure web root directory exists
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create nginx configuration template
      copy:
        content: |
          server {
              listen 80;
              server_name {{ server_name }};
              root {{ web_root }};
              index {{ index_page }};

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        dest: /etc/ansible/nginx_default.j2
        owner: root
        group: root
        mode: '0644'

    - name: Configure nginx
      template:
        src: /etc/ansible/nginx_default.j2
        dest: "{{ nginx_config_path }}"
      notify: Restart Nginx

    - name: Create a soft link in the enabled sites
      file:
        src: "{{ nginx_config_path }}"
        dest: /etc/nginx/sites-enabled/default_new
        state: link

    - name: Create index.html file
      copy:
        content: "<html><body><h1>Hello World</h1></body></html>"
        dest: "{{ web_root }}/index.html"
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      listen: "nginx needs restart"
